name: Auto Build FFmpeg
on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Msys2
        uses: msys2/setup-msys2@v2
        with:
          location: D:\
          msystem: msys
          update: true
          install: make pkgconf diffutils mingw-w64-x86_64-nasm mingw-w64-x86_64-gcc mingw-w64-x86_64-SDL2
      - name: Setup Mingw64
        uses: msys2/setup-msys2@v2
        with:
          location: D:\
          msystem: mingw64
          install: git
      - name: Download FFmpeg Source Code
        shell: msys2 {0}
        run: |
          cd /d/msys64/
          git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg/
      - name: Build FFmpeg
        shell: msys2 {0}
        run: |
          cd /d/msys64/ffmpeg
          ./configure --enable-static --disable-shared --prefix=/usr/local/ffmpeg && make -j4 && make install
      - name: Zip
        shell: cmd
        run: |
          copy D:\msys64\mingw64\bin\*.dll D:\msys64\usr\local\ffmpeg\bin
          7z a -tzip D:\ffmpeg.zip D:\msys64\usr\local\ffmpeg\*
      - name: Create a Tag
        id: tag
        run: echo "::set-output name=tagname::Auto-Build-FFmpeg-On-$(date +"%Y/%m/%d_%H-%M")"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.tagname }}
          body: Auto build FFmpeg
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: D:\ffmpeg.zip
