name: Auto Build FFmpeg
on:
  push:
    branches: 
        - main
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: false
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
      - name: Setup Msys2
        uses: msys2/setup-msys2@v2
        with:
          location: D:\
          msystem: msys
          update: true
          install: make pkgconf diffutils mingw-w64-x86_64-nasm mingw-w64-x86_64-gcc mingw-w64-x86_64-SDL2
      - name: Setup Mingw64
        uses: msys2/setup-msys2@v2
        with:
          location: D:\
          msystem: mingw64
          install: git
      - name: Download FFmpeg Source Code
        shell: msys2 {0}
        run: |
          cd /d/msys64/
          git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg\
      - name: Build FFmpeg
        shell: msys2 {0}
        run: |
          cd d/msys64/ffmpeg
          ./configure --enable-static --disable-shared --prefix=/usr/local/ffmpeg && make -j 4 && make install
      - name: Zip
        shell: cmd
        run: |
          copy D:\msys64\mingw64\lib\*.dll D:\msys64\usr\local\ffmpeg\bin
          7z -tzip D:\ffmpeg.zip D:\msys64\usr\local\ffmpeg\*
